name: Ruff

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ruff
        uses: chartboost/ruff-action@v1
